### ISSUE TITLE
Motor positions updating after disconnection

### ISSUE THREAD

**Issue by Fedefreez** [MakerStation/FabCatApp#6]
**Describe the bug**
The motor potisions on motorsfragment will update after disconnection if we click on a position in positionsfragment.

**To Reproduce**
1. Go to 'Motors'
2. Disconnect cat
3. Wait for disconnection notice
4. Go to 'Positions'
5. Click on any positions
6. profit

**Expected behavior**
The values don't update since the cat isn't connected.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S5 neo
 - OS: android 6.0.2
 - Version 3.7 build 23

**Comment by Sintuz** [comment]
Bug fixed in commit 963bfb765266a27ea1a98eadadf91129e32d3683
